package constants

const (
	Primary     = "PRIMARY"
	Adjustment  = "ADJUSTMENT"
	Endorsement = "ENDORSEMENT"

	Pending         = "PENDING"
	SentToNextStage = "SENT TO NEXT STAGE"
	Rejected        = "REJECTED"
	Approved        = "APPROVED"
	Pushback        = "PUSHBACK"

	TransactionType         = "transaction_type"
	RmCode                  = "rm_code"
	RmName                  = "rm_name"
	ChildID                 = "child_id"
	BookingDate             = "booking_date"
	InsurerName             = "insurer_name"
	InsuredName             = "insured_name"
	MajorCategory           = "major_category"
	Product                 = "product"
	ProductType             = "product_type"
	PolicyNumber            = "policy_number"
	PlanType                = "plan_type"
	Premium                 = "premium"
	NetPremium              = "net_premium"
	OD                      = "od"
	TP                      = "tp"
	CommissionablePremium   = "commissionable_premium"
	RegistrationNo          = "registration_no"
	RTOCode                 = "rto_code"
	State                   = "state"
	RTOCluster              = "rto_cluster"
	City                    = "city"
	InsurerBiff             = "insurer_biff"
	FuelType                = "fuel_type"
	CPA                     = "cpa"
	CC                      = "cc"
	GVW                     = "gvw"
	NCBType                 = "ncb_type"
	SeatingCapacity         = "seating_capacity"
	VehicleRegistrationYear = "vehicle_registration_year"
	DiscountInPercentage    = "discount_in_percentage"
	Make                    = "make"
	Model                   = "model"
	CTG                     = "ctg"
	IDV                     = "idv"
	SumInsuredVal           = "sum_insured_val"
	UniqueID                = "unique_id"
	VehicleRegistrationDate = "vehicle_registration_date"
	UTR                     = "utr"
	UTRDate                 = "utr_date"
	UTRAmount               = "utr_amount"
	SlotPaymentBatch        = "slot_payment_batch"
	PaidOnIn                = "paid_on_in"
	TentativeInPercentage   = "tentative_in_percentage"
	TentativeInAmount       = "tentative_in_amount"
	PaidOnOut               = "paid_on_out"
	OutPercentage           = "out_percentage"
	OutAmount               = "out_amount"
	COType                  = "co_type"
	Remarks                 = "remarks"
)
