package constants

const (
	Primary     = "PRIMARY"
	Adjustment  = "ADJUSTMENT"
	Endorsement = "ENDORSEMENT"

	Pending         = "PENDING"
	SentToNextStage = "SENT TO NEXT STAGE"
	Rejected        = "REJECTED"
	Approved        = "APPROVED"
	Pushback        = "PUSHBACK"

	TransactionType         = "TransactionType"
	RmCode                  = "RmCode"
	RmName                  = "RmName"
	ChildID                 = "ChildID"
	BookingDate             = "BookingDate"
	InsurerName             = "InsurerName"
	InsuredName             = "InsuredName"
	MajorCategory           = "MajorCategory"
	Product                 = "Product"
	ProductType             = "ProductType"
	PolicyNumber            = "PolicyNumber"
	PlanType                = "PlanType"
	Premium                 = "Premium"
	NetPremium              = "NetPremium"
	OD                      = "OD"
	TP                      = "TP"
	CommissionablePremium   = "CommissionablePremium"
	RegistrationNo          = "RegistrationNo"
	RTOCode                 = "RTOCode"
	State                   = "State"
	RTOCluster              = "RTOCluster"
	City                    = "City"
	InsurerBiff             = "InsurerBiff"
	FuelType                = "FuelType"
	CPA                     = "CPA"
	CC                      = "CC"
	GVW                     = "GVW"
	NCBType                 = "NCBType"
	SeatingCapacity         = "SeatingCapacity"
	VehicleRegistrationYear = "VehicleRegistrationYear"
	DiscountInPercentage    = "DiscountInPercentage"
	Make                    = "Make"
	Model                   = "Model"
	CTG                     = "CTG"
	IDV                     = "IDV"
	SumInsuredVal           = "SumInsuredVal"
	UniqueID                = "UniqueId"
	VehicleRegistrationDate = "VehicleRegistrationDate"
	UTR                     = "UTR"
	UTRDate                 = "UTRDate"
	UTRAmount               = "UTRAmount"
	SlotPaymentBatch        = "SlotPaymentBatch"
	PaidOnIn                = "PaidOnIn"
	TentativeInPercentage   = "TentativeInPercentage"
	TentativeInAmount       = "TentativeInAmount"
	PaidOnOut               = "PaidOnOut"
	OutPercentage           = "OutPercentage"
	OutAmount               = "OutAmount"
	COType                  = "COType"
	Remarks                 = "Remarks"

	Failure = "Failure"
	Success = "Success"
)
