package constants

var MOTOR_MAKER_CSV_TO_MODEL_MAP = map[string]interface{}{
	"RM code":                            "rm_code",
	"RM Name1":                           "rm_name",
	"Child ID":                           "child_id",
	"Booking Date(Click to select Date)": "booking_date",
	"Insurer Name":                       "insurer_name",
	"Insured Name":                       "insured_name",
	"Major Categorisation( Motor/Life/ Health)": "major_category",
	"Product":                            "product",
	"Product type":                       "product_type",
	"Policy number":                      "policy_number",
	"Plan type":                          "plan_type",
	"Premium":                            "premium",
	"Net premium":                        "net_premium",
	"OD":                                 "od",
	"TP":                                 "tp",
	"Commissionable premium":             "commissionable_premium",
	"Registrationno":                     "registration_no",
	"RTO Code":                           "rto_code",
	"State":                              "state",
	"RTO Cluster":                        "rto_cluster",
	"City":                               "city",
	"Insurer_biff":                       "insurer_biff",
	"Fuel type":                          "fuel_type",
	"CPA":                                "cpa",
	"CC":                                 "cc",
	"GVW":                                "gvw",
	"NCB Type":                           "ncb_type",
	"Seating Capacity":                   "seating_capacity",
	"Vehicle registration year":          "vehicle_registration_year",
	"Discount %":                         "discount_in_percentage",
	"Make":                               "make",
	"Model":                              "model",
	"CTG":                                "ctg",
	"IDV":                                "idv",
	"Sum Insured Value":                  "sum_insured_val",
	"Unique ID":                          "unique_id",
	"Vehicle registration Date":          "vehicle_registration_date",
	"UTR":                                "utr",
	"UTR Date":                           "utr_date",
	"UTR Amount":                         "utr_amount",
	"Slot (Payment batch)":               "slot_payment_batch",
	"Paid On IN":                         "paid_on_in",
	"Tentative_IN%":                      "tentative_in_percentage",
	"Tentative_IN Amount":                "tentative_in_amount",
	"Paid On Out":                        "paid_on_out",
	"Out%":                               "out_percentage",
	"Out Amount":                         "out_amount",
	"Co type ( ZIBPL/I CARE/Individual)": "co_type",
	"Remarks":                            "remarks",
}
