package constants

var MotorMakerCSVToModelMap = map[string]string{
	"Transaction Type":                   TransactionType,
	"RM code":                            RmCode,
	"RM Name1":                           RmName,
	"Child ID":                           ChildID,
	"Booking Date(Click to select Date)": BookingDate,
	"Insurer Name":                       InsurerName,
	"Insured Name":                       InsuredName,
	"Major Categorisation( Motor/Life/ Health)": MajorCategory,
	"Product":                            Product,
	"Product type":                       ProductType,
	"Policy number":                      PolicyNumber,
	"Plan type":                          PlanType,
	"Premium":                            Premium,
	"Net premium":                        NetPremium,
	"OD":                                 OD,
	"TP":                                 TP,
	"Commissionable premium":             CommissionablePremium,
	"Registrationno":                     RegistrationNo,
	"RTO Code":                           RTOCode,
	"State":                              State,
	"RTO Cluster":                        RTOCluster,
	"City":                               City,
	"Insurer_biff":                       InsurerBiff,
	"Fuel type":                          FuelType,
	"CPA":                                CPA,
	"CC":                                 CC,
	"GVW":                                GVW,
	"NCB Type":                           NCBType,
	"Seating Capacity":                   SeatingCapacity,
	"Vehicle registration year":          VehicleRegistrationYear,
	"Discount %":                         DiscountInPercentage,
	"Make":                               Make,
	"Model":                              Model,
	"CTG":                                CTG,
	"IDV":                                IDV,
	"Sum Insured Value":                  SumInsuredVal,
	"Unique ID":                          UniqueID,
	"Vehicle registration Date":          VehicleRegistrationDate,
	"UTR":                                UTR,
	"UTR Date":                           UTRDate,
	"UTR Amount":                         UTRAmount,
	"Slot (Payment batch)":               SlotPaymentBatch,
	"Paid On IN":                         PaidOnIn,
	"Tentative_IN%":                      TentativeInPercentage,
	"Tentative_IN Amount":                TentativeInAmount,
	"Paid On Out":                        PaidOnOut,
	"Out%":                               OutPercentage,
	"Out Amount":                         OutAmount,
	"Co type ( ZIBPL/I CARE/Individual)": COType,
	"Remarks":                            Remarks,
}

var MotorMandatoryFields = []string{
	TransactionType, PolicyNumber, BookingDate, Premium,
	NetPremium, VehicleRegistrationYear, TentativeInPercentage,
	InsurerName, Product}

var MotorInsurerJsonData = map[string]map[string][]string{
	"hdfc ergo": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"rto_cluster",
			"cpa",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"ncb_type",
			"cc",
			"vehicle_registration_year",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"discount_in_percentage",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"zuno": {
		"2W": {},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"icici lombard": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"make",
			"model",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"digit insurance": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"cc",
			"make",
			"model",
			"rto_cluster",
			"ctg",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"cc",
			"make",
			"model",
			"rto_cluster",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"gvw",
			"vehicle_registration_year",
			"discount_in_percentage",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
			"rto_cluster",
		},
	},
	"tata": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"make",
			"model",
			"vehicle_registration_year",
			"rto_cluster",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"rto_cluster",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
			"rto_cluster",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
			"rto_cluster",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
			"rto_cluster",
		},
	},
	"liberty general insurance": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv":  {},
		"misc": {},
	},
	"sbi": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"royal sundaram general insurance": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {},
	},
	"shriram general insurance": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"chola": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"magma hdi general insurance": {
		"2W": {
			"booking_date",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"state",
			"cc",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"universal sompo general insurance company": {
		"2W": {},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"seating_capacity",
			"vehicle_registration_year",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
	},
	"reliance general insurance": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"cc",
			"make",
			"model",
			"rto_cluster",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"cc",
			"make",
			"model",
			"rto_cluster",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"seating_capacity",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"misc": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
	},
	"future generali india insurance": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"cc",
			"make",
			"model",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"cc",
			"make",
			"model",
			"rto_cluster",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
		"misc": {},
	},
	"raheja": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"cc",
			"make",
			"model",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
			"cc",
			"make",
			"model",
			"ncb_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
			"make",
			"model",
		},
		"pcv":  {},
		"misc": {},
	},
	"new india": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
		},
		"pcv":  {},
		"misc": {},
	},
	"united": {
		"2W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"vehicle_registration_year",
		},
		"4W": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"fuel_type",
		},
		"gcv": {
			"booking_date",
			"insurer_name",
			"product",
			"product_type",
			"plan_type",
			"premium",
			"net_premium",
			"od",
			"registration_no",
			"rto_code",
			"gvw",
			"vehicle_registration_year",
		},
		"pcv":  {},
		"misc": {},
	},
}
