version: '3.8'

services:
  web:
    build: .
    container_name: go-fdms_web
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/srv/app
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: go-fdms_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
